minimumReleaseAge: 1440
blockExoticSubdeps: false

allowBuilds:
  '@ffmpeg-installer/linux-x64': true
  '@electron/rebuild': true
  better-sqlite3: true
  electron: true
  electron-winstaller: true
  esbuild: true
